# Generated by Django 5.1.1 on 2025-01-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0003_admin_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='subject',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='score',
        ),
    ]
