# Generated by Django 5.1.1 on 2025-01-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thirdapp', '0009_alter_student1_dob_alter_student1_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_text', models.CharField(max_length=50)),
                ('full_text', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('medium_text', models.CharField(max_length=50)),
                ('prime_text', models.CharField(max_length=50)),
                ('free_text', models.CharField(max_length=30)),
                ('offer', models.CharField(max_length=50)),
                ('service_text', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Card',
            },
        ),
    ]
